<?php
		define('DB_HOST','localhost');
		define('DB_USER','root');
		define('DB_PWD','');
		define('DB_CHARSET','utf8');
		define('DB_NAME','pjceshi');
		define('DB_PREFIX','');
		//设置时区
		date_default_timezone_set('PRC');